name: trigger-learnings

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: string
      version:
        description: "Version"
        required: true
        type: string
  # schedule:
  #   - cron: "*/10 * * * *"

jobs:
  test:
    name: learn
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Input Environment: ${{ inputs.environment }}"
          echo "Input Version: ${{ inputs.version }}"

          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Event: ${{ github.event_name }}"

          echo "Repo Variable: ${{ vars.ENVIRONMENT }}"

          echo "Api token: ${{ secrets.API_TOKEN }}"