name: trigger-learnings

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - opened
  workflow_dispatch:
    inputs:
    environment:
      description: "Environment"
      required: true
      type: string
    version:
      description: "Version"
      required: true
      type: string
  # schedule:
  #   - cron: "*/10 * * * *"

jobs:
  test:
    name: learn
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ inputs.environment }}"
          echo "${{ inputs.version }}"
